version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_2005_175Project
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_2005_175.integrations:refdaf
  packages:
  - name: Kvv_2005_175Project
    version: "1.0"
- serviceName: project.kvv_2005_175.referencedata:ref1
  packages:
  - name: Kvv_2005_175Project
    version: "1.0"
